const characterList = [
    "Abomination",
    "Absorbing Man",
    "Adam Warlock",
    "Agatha Harkness",
    "Agent Coulson",
    "America Chavez",
    "Angel",
    "Ant-Man (Lang)",
    "Apocalypse",
    "Avengers",
    "Banshee",
    "Barracuda",
    "Beast",
    "Ben Reilly",
    "Beta Ray Bill",
    "Bishop",
    "Black Bolt",
    "Black Cat",
    "Black Knight",
    "Black Panther",
    "Black Widow",
    "Blackheart",
    "Blade",
    "Blue Marvel",
    "Bucky Barnes",
    "Bullseye",
    "Cable",
    "Captain America",
    "Captain Britain",
    "Captain Marvel",
    "Carnage",
    "Carol Danvers",
    "Cassie Lang",
    "Chameleon",
    "Cloak",
    "Colossus",
    "Cyclops",
    "Dagger",
    "Daken",
    "Daredevil",
    "Deadpool",
    "Doctor Doom",
    "Doctor Octopus",
    "Doctor Strange",
    "Drax",
    "Dum Dum Dugan",
    "Eddie Brock",
    "Electro",
    "Elektra",
    "Falcon",
    "Flash Thompson",
    "Galactus",
    "Gambit",
    "Gamora",
    "Ghost Rider (Blaze)",
    "Green Goblin",
    "Groot",
    "Hank Pym",
    "Havok",
    "Hawkeye",
    "Heimdall",
    "Hercules",
    "Hobgoblin",
    "Howard the Duck",
    "Hulk",
    "Hulkling",
    "Human Torch",
    "Iceman",
    "Invisible Woman",
    "Iron Fist",
    "Iron Heart",
    "Iron Man",
    "Jean Grey",
    "Jessica Jones",
    "Jigsaw",
    "Jubilee",
    "Juggernaut",
    "Ka-Zar",
    "Kaine",
    "Kingpin",
    "Korg",
    "Kitty Pryde",
    "Kraven the Hunter",
    "Lady Deathstrike",
    "Lady Thor",
    "Lizard",
    "Lockheed",
    "Loki",
    "Luke Cage",
    "Madrox",
    "Magneto",
    "Mandarin",
    "Mephisto",
    "Miles Morales",
    "Mockingbird",
    "Molten Man",
    "Moon Knight",
    "Morbius",
    "Mr. Fantastic",
    "Mr. Immortal",
    "Mr. Sinister",
    "Mysterio",
    "Mystique",
    "Namor",
    "Nick Fury",
    "Nightcrawler",
    "Noh-Varr",
    "Nova",
    "Obadiah Stane",
    "Odin",
    "Okoye",
    "Omega Red",
    "Onslaught",
    "Patriot",
    "Phil Coulson",
    "Prodigy",
    "Professor X",
    "Prowler",
    "Punisher",
    "Pyro",
    "Quake",
    "Quicksilver",
    "Red Skull",
    "Rhino",
    "Rick Jones",
    "Rocket Raccoon",
    "Rogue",
    "Sabretooth",
    "Sandman",
    "Scarlet Witch",
    "Scorpion",
    "Sebastian Shaw",
    "Sentry",
    "Shang-Chi",
    "She-Hulk",
    "Shuri",
    "Silver Sable",
    "Silver Samurai",
    "Silver Surfer",
    "Star-Lord",
    "Storm",
    "Speedball",
    "Spider-Girl (Parker)",
    "Spider-Man",
    "Spider-Man 2099",
    "Spider-Woman",
    "Squirrel Girl",
    "Storm",
    "Super-Skrull",
    "Swordsman",
    "Taskmaster",
    "Thanos",
    "The Hood",
    "Thing",
    "Thor",
    "Thunderbolt Ross",
    "Toxin",
    "Ultron",
    "Union Jack",
    "Venom",
    "Vision",
    "Vulcan",
    "War Machine",
    "Wasp",
    "White Tiger",
    "Wiccan",
    "William Stryker",
    "Wolverine",
    "Wonder Man",
    "X-23",
    "Yondu",
]

export default characterList;