const characterList = [
    "Abomination",
    "Absorbing Man",
    "Angel",
    "Ant-Man (Lang)",
    "Apocalypse",
    "Banshee",
    "Barracuda",
    "Beast",
    "Ben Reilly",
    "Beta Ray Bill",
    "Bishop",
    "Black Bolt",
    "Black Cat",
    "Black Knight",
    "Black Panther",
    "Black Widow",
    "Blackheart",
    "Blade",
    "Bucky Barnes",
    "Bullseye",
    "Cable",
    "Captain America",
    "Captain Britain",
    "Captain Marvel",
    "Carnage",
    "Carol Danvers",
    "Cassie Lang",
    "Chameleon",
    "Cloak",
    "Colossus",
    "Cyclops",
    "Dagger",
    "Daken",
    "Daredevil",
    "Doctor Doom",
    "Doctor Octopus",
    "Doctor Strange",
    "Dum Dum Dugan",
    "Eddie Brock",
    "Electro",
    "Elektra",
    "Flash Thompson",
    "Galactus",
    "Gambit",
    "Ghost Rider (Blaze)",
    "Hank Pym",
    "Havok",
    "Hawkeye",
    "Hercules",
    "Hobgoblin (Kingsley)",
    "Howard the Duck",
    "Hulk",
    "Hulkling",
    "Human Torch",
    "Iceman",
    "Invisible Woman",
    "Iron Fist",
    "Iron Man",
    "Jean Grey",
    "Jigsaw",
    "Jubilee",
    "Juggernaut",
    "Ka-Zar",
    "Kaine",
    "Kingpin",
    "Kitty Pryde",
    "Kraven the Hunter",
    "Lady Deathstrike",
    "Lizard",
    "Lockheed",
    "Loki",
    "Luke Cage",
    "Madrox",
    "Magneto",
    "Mandarin",
    "Mephisto",
    "Miles Morales",
    "Mockingbird",
    "Molten Man",
    "Moon Knight",
    "Morbius",
    "Mr. Fantastic",
    "Mr. Immortal",
    "Mr. Sinister",
    "Mysterio",
    "Mystique",
    "Namor",
    "Nick Fury",
    "Nightcrawler",
    "Noh-Varr",
    "Nova",
    "Obadiah Stane",
    "Odin",
    "Omega Red",
    "Onslaught",
    "Patriot",
    "Phil Coulson",
    "Prodigy",
    "Professor X",
    "Prowler",
    "Punisher",
    "Pyro",
    "Quicksilver",
    "Red Skull",
    "Rhino",
    "Rick Jones",
    "Rogue",
    "Sabretooth",
    "Sandman",
    "Scarlet Witch",
    "Scorpion",
    "Sebastian Shaw",
    "Sentry",
    "She-Hulk",
    "Silver Sable",
    "Silver Samurai",
    "Silver Surfer",
    "Speedball",
    "Spider-Girl (Parker)",
    "Spider-Man",
    "Spider-Man 2099",
    "Spider-Woman",
    "Squirrel Girl",
    "Storm",
    "Super-Skrull",
    "Swordsman",
    "Taskmaster",
    "Thanos",
    "The Hood",
    "Thing",
    "Thor",
    "Thunderbolt Ross",
    "Toxin",
    "Ultron",
    "Union Jack",
    "Venom",
    "Vision",
    "Vulcan",
    "War Machine",
    "Wasp",
    "White Tiger",
    "Wiccan",
    "William Stryker",
    "Wolverine",
    "Wonder Man",
    "X-23",
]

export default characterList;